apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 8080
    nodePort: 30006
  selector:
    app: jupyter-notbook
  
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  labels:
    app: jupyter-notebook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
        - name: jupyter-notebook
          image: eyasped/jupyter-notebook
          ports:
          - containerPort: 8080